title: Chaofan Wang
description: Postdoctoral Researcher at TU Delft
theme: just-the-docs

url: "https://chaofanqw.github.io"

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
